### ISSUE TITLE
[Pesquisa] - Android Studio

### ISSUE THREAD

**Issue by ehcamero** [ehcamero/Busca-em-profundidade#2]
- Fontes pesquisadas
- Arquivos gerados

**Comment by jeffersonamoriim** [comment]
[Desenvolvimento_Android.txt](https://github.com/ehcamero/Busca-em-profundidade/files/1852702/Desenvolvimento_Android.txt)

**Comment by jeffersonamoriim** [comment]
[opencv_test.zip](https://github.com/ehcamero/Busca-em-profundidade/files/1887756/opencv_test.zip)
